### ISSUE TITLE
Metadata properties related to the content of the model make more sense in the core

### ISSUE THREAD

**Issue by liberostelios** [cityjson/metadata-extended#1]
In my opinion, some of the properties extracted here should remain in the core of CityJSON. This is mostly for things that can significantly help with parsing/manipulating CityJSON for developers, like:

- textures (absent/present)
- materials (absent/present)
- thematicModels

I'd rather embrace the use of these properties, as soon as they aren't too complex, than marginalise them.

**Comment by hugoledoux** [comment]
The idea was to keep the core with metadata that can *not* be extracted automatically. Textures/materials can be extracted automatically and thus will often not be insync with the model if the user is not aware.

I'm not sure about the 6 I picked in draft, maybe contactPoint should be there.

**Comment by balazsdukai** [comment]
I think this is a bit subjective, because certain metadata can be less or more important to different people. So I'll approach it from my point of view as well.

Usually when I look into a data set, I want to know these things:

+ When was it created / how old is the information within ?
+ Who made it? Because I want to know if I can trust the data and data creator.

Then specific to cityjson, I need info on how to process the file:

+ CRS
+ Should I expect triangulated surfaces or not? Not knowing this can be problematic if my code expects triangles, and checking it upfront is cumbersome I think.

Then there are nice things to have, that make the data processing even easier:

+ Some unique ID for the data
+ BBOX of the data

In my opinion, these should be in the core. The rest of the info I think I can get relatively easily while processing the file.

**Comment by liberostelios** [comment]
> I think this is a bit subjective, because certain metadata can be less or more important to different people. So I'll approach it from my point of view as well.
> 
> Usually when I look into a data set, I want to know these things:
> 
>     * When was it created / how old is the information within ?
> 
>     * Who made it? Because I want to know if I can trust the data and data creator.
> 
> 
> Then specific to cityjson, I need info on how to process the file:
> 
>     * CRS
> 
>     * Should I expect triangulated surfaces or not? Not knowing this can be problematic if my code expects triangles, and checking it upfront is cumbersome I think.
> 
> 
> Then there are nice things to have, that make the data processing even easier:
> 
>     * Some unique ID for the data
> 
>     * BBOX of the data
> 
> 
> In my opinion, these should be in the core. The rest of the info I think I can get relatively easily while processing the file.

I agree with your pov. And indeed this is a subjective matter. But from my experience the existence of textures/materials and their default theme is as important as the triangulation. Maybe even more important, actually, since this heavily dectates how one might handle the content of the file even if they don't manipulate the geometry.

**Comment by hugoledoux** [comment]
okay, I think we could argue ad vitam eternam about what should be in the core, but this is not super useful since all the properties can be stored in one-click with `cjio metadata_create`.

So I've decided that those 6 properties are in the core, they seem to be the most common things people expect and cannot be calculated/extracted (except bbox but this is "standard").

```json
"metadata": {
  "citymodelIdentifier": "eaeceeaa-3f66-429a-b81d-bbc6140b8c1c",
  "datasetPointOfContact": {
    "contactName": "3D geoinformation group, Delft University of Technology",
    "contactType": "organization",
    "role": "owner",
    "phone": "+31-6666666666",
    "emailAddress": "3dgeoinfo-bk@tudelft.nl",
    "website": "https://3d.bk.tudelft.nl",
    "address": "Julianalaan 134, Delft 2628BL, the Netherlands"
  },
  "datasetReferenceDate": "1977-02-28",
  "datasetTitle": "Buildings in LoD2.3 of Chibougamau, Québec",
  "geographicalExtent": [ 84710.1, 446846.0, -5.3, 84757.1, 446944.0, 40.9 ],
  "referenceSystem": "https://www.opengis.net/def/crs/EPSG/0/2355"
}
```

"triangulated" and "textures" and "materials" are now all properties of the metadata-extended
